name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  PURS_BUILD_VERSION: v0.14.5

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        purs_test_version: [v0.12.0, v0.12.4, v0.12.5, v0.13.0, v0.14.0, v0.14.5]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      PURS_TEST_VERSION: ${{ matrix.purs_test_version }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "non-Windows - Download PureScript (Build version)"
        shell: bash
        if: runner.os != 'Windows'
        run: |
          DIR=$HOME/bin/purescript-$PURS_BUILD_VERSION
          mkdir -p $DIR
          wget -O $DIR/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_BUILD_VERSION/linux64.tar.gz
          tar -xvf $DIR/purescript.tar.gz -C $DIR --strip-components 1 purescript/purs
          chmod a+x $DIR/purs

      - name: "non-Windows - Download PureScript (Test version)"
        if: runner.os != 'Windows' && env.PURS_BUILD_VERSION != env.PURS_TEST_VERSION
        shell: bash
        run: |
          DIR=$HOME/bin/purescript-$PURS_TEST_VERSION
          mkdir -p $DIR
          wget -O $DIR/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_TEST_VERSION/linux64.tar.gz
          tar -xvf $DIR/purescript.tar.gz -C $DIR --strip-components 1 purescript/purs
          chmod a+x $DIR/purs

      - name: "non-Windows - Run NPM install"
        if: runner.os != 'Windows'
        run: |
          echo "Using Purs with version:"
          PATH="$HOME/bin/purescript-$PURS_BUILD_VERSION:$PATH"
          purs --version
          npm install

      - name: "non-Windows - Run NPM test (unit)"
        if: runner.os != 'Windows'
        run: |
          echo "Using Purs with version:"
          PATH="$HOME/bin/purescript-$PURS_BUILD_VERSION:$PATH"
          purs --version
          npm run test:unit

      - name: "non-Windows - Run NPM test (integration)"
        if: runner.os != 'Windows'
        run: |
          echo "Using Purs with version:"
          PATH="$HOME/bin/purescript-$PURS_TEST_VERSION:$PATH"
          purs --version
          npm run test:integration


      - name: "Windows - Download PureScript (Build version)"
        shell: bash
        if: runner.os == 'Windows'
        run: |
          pushd C:\\tools
          DIR=purescript-$PURS_BUILD_VERSION
          mkdir -p $DIR
          curl -opurescript.tar.gz -L https://github.com/purescript/purescript/releases/download/$PURS_BUILD_VERSION/win64.tar.gz
          tar -xvzf purescript.tar.gz -C $DIR --strip-components 1 purescript/purs.exe
          ls .
          ls purescript-$PURS_BUILD_VERSION
          popd

      - name: "Windows - Download PureScript (Test version)"
        if: runner.os == 'Windows' && env.PURS_BUILD_VERSION != env.PURS_TEST_VERSION
        shell: bash
        run: |
          pushd C:\\tools
          DIR=purescript-$PURS_TEST_VERSION
          mkdir -p $DIR
          curl -opurescript.tar.gz -L https://github.com/purescript/purescript/releases/download/$PURS_TEST_VERSION/win64.tar.gz
          tar -xvzf purescript.tar.gz -C $DIR --strip-components 1 purescript/purs.exe
          popd

      - name: "Windows - Run NPM install"
        if: runner.os == 'Windows'
        run: |
          echo "Using Purs with version:"
          $env:Path="C:\tools\purescript-$env:PURS_BUILD_VERSION;$env:Path"
          purs.exe --version
          npm install

      - name: "Windows - Run NPM test (unit)"
        if: runner.os == 'Windows'
        run: |
          echo "Using Purs with version:"
          $env:Path="C:\tools\purescript-$env:PURS_BUILD_VERSION;$env:Path"
          purs.exe --version
          npm run test:unit

      - name: "Windows - Run NPM test (integration)"
        if: runner.os == 'Windows'
        run: |
          echo "Using Purs with version:"
          $env:Path="C:\tools\purescript-$env:PURS_TEST_VERSION;$env:Path"
          purs.exe --version
          npm run test:integration
